---
title: "36-315 Static Graphics Project"
author: "Andrew Lee, Weng Shian Ho, Daniel Liu, Yeju Ahn"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  hide
---


+  A link to the dataset:




```{r, message=FALSE}
library(tidyverse)
library(igraph)
library(igraphdata)
library(dendextend)
```

* CSV FILE
```{r, message = FALSE}
suicide_data <- read.csv("suicide-dataset.csv")
dim(suicide_data)
nrow(suicide_data)
ncol(suicide_data)
```

#Choropleth Map (Siheon)

```{r}
countries <- map_data("world2")
country_list <- unique(suicide_data$country)
country_cords <- data.frame()
for (i in 1:length(country_list)){
  curr.country <- country_list[i]
  curr.country.data <- countries[which(countries$region == curr.country),]
  curr.avg.lat <- mean(curr.country.data$lat)
  curr.avg.long <- mean(curr.country.data$long)
  curr.avg.grp <- round(median(curr.country.data$group))
  curr.dist <- data.frame(Country = curr.country, Lat = curr.avg.lat, long =  curr.avg.long, group = curr.avg.grp)
  country_cords <- rbind(country_cords, curr.dist)
}

#Manually fill in entries not found

country_cords[which(country_cords$Country == 'Republic of Korea'),2] <- mean(countries[which(countries$region == "South Korea"),2])
country_cords[which(country_cords$Country == 'Republic of Korea'),3] <- mean(countries[which(countries$region == "South Korea"),1])
country_cords[which(country_cords$Country == 'Republic of Korea'),4] <- round(median(countries[which(countries$region == "South Korea"),3]))

country_cords[which(country_cords$Country == 'United States'),2] <- mean(countries[which(countries$region == "USA"),2])
country_cords[which(country_cords$Country == 'United States'),3] <- mean(countries[which(countries$region == "USA"),1])
country_cords[which(country_cords$Country == 'United States'),4] <- round(median(countries[which(countries$region == "USA"),3]))

country_cords[which(country_cords$Country == 'Trinidad and Tobago'),2] <- mean(countries[which(countries$region == "Trinidad" | countries$region == "Tobago"),2])
country_cords[which(country_cords$Country == 'Trinidad and Tobago'),3] <- mean(countries[which(countries$region == "Trinidad" | countries$region == "Tobago"),1])
country_cords[which(country_cords$Country == 'Trinidad and Tobago'),4] <- round(median(countries[which(countries$region == "Trinidad" | countries$region == "Tobago"),3]))

country_cords[which(country_cords$Country == 'Russian Federation'),2] <- mean(countries[which(countries$region == "Russia"),2])
country_cords[which(country_cords$Country == 'Russian Federation'),3] <- mean(countries[which(countries$region == "Russia"),1])
country_cords[which(country_cords$Country == 'Russian Federation'),4] <- round(median(countries[which(countries$region == "Russia"),3]))

country_cords[which(country_cords$Country == 'Saint Kitts and Nevis'),2] <- mean(countries[which(countries$region == "Saint Kitts" | countries$region == "Nevis"),2])
country_cords[which(country_cords$Country == 'Saint Kitts and Nevis'),3] <- mean(countries[which(countries$region == "Saint Kitts" | countries$region == "Nevis"),1])
country_cords[which(country_cords$Country == 'Saint Kitts and Nevis'),4] <- round(median(countries[which(countries$region == "Saint Kitts" | countries$region == "Nevis"),3]))

country_cords[which(country_cords$Country == 'Saint Vincent and Grenadines'),2] <- mean(countries[which(countries$region == "Saint Vincent" | countries$region == "Grenadines"),2])
country_cords[which(country_cords$Country == 'Saint Vincent and Grenadines'),3] <- mean(countries[which(countries$region == "Saint Vincent" | countries$region == "Grenadines"),1])
country_cords[which(country_cords$Country == 'Saint Vincent and Grenadines'),4] <- round(median(countries[which(countries$region == "Saint Vincent" | countries$region == "Grenadines"),3]))

country_cords[which(country_cords$Country == 'Antigua and Barbuda'),2] <- mean(countries[which(countries$region == "Antigua" | countries$region == "Barbuda"),2])
country_cords[which(country_cords$Country == 'Antigua and Barbuda'),3] <- mean(countries[which(countries$region == "Antigua" | countries$region == "Barbuda"),1])
country_cords[which(country_cords$Country == 'Antigua and Barbuda'),4] <- round(median(countries[which(countries$region == "Antigua" | countries$region == "Barbuda"),3]))
```

#Dendrogram and Clustering (Weng and Daniel)

```{r}
#Plan: Shall just look at 2015--> Look at the weighted average suicide rates and make a dendrogram plot based-off that

#Edit sucide data
suicides.2015 <- suicide_data[which(suicide_data$year == 2015),]
country_list <- unique(suicides.2015$country)

country.suicides.2015 <- data.frame()

for (i in 1:length(country_list)){
  curr.country <- country_list[i]
  curr.country.data <- suicides.2015[which(suicides.2015$country == curr.country),]
  curr.suicide.rate <-  sum(curr.country.data$suicides_no/curr.country.data$population)
  curr.data.frame <- data.frame(Country = curr.country, Rate = curr.suicide.rate)
  country.suicides.2015 <- rbind(country.suicides.2015,curr.data.frame)
}

all.suicides.2015.data <- merge(country.suicides.2015,country_cords, by = intersect("Country", "Country"))
```



#Dendrogram Plot
```{r}
clusters <- hclust(dist(all.suicides.2015.data))
clusterCut <- cutree(clusters, 3)
clusterCut.2 <- cutree(clusters, 2)
table(clusterCut, country.suicides.2015$Country)
country.suicides.2015$Group.3 <- clusterCut
country.suicides.2015$Group.2 <- clusterCut.2
```

```{r}
dend <- country.suicides.2015$Rate %>% scale %>% dist %>% hclust %>% as.dendrogram
ggplot(dend, horiz = F)
```


# draw map 
```{r}
library(ggsn)
colnames(all.suicides.2015.data)[which(names(all.suicides.2015.data) == "Country")] <- "region"
little_data <- select(all.suicides.2015.data, region, Rate)
new_data <- left_join(countries, little_data, by = "region")

# Converts a numeric array to an array of latitude labels
latitude <- function(x)
    paste0(format(x, digits = 3), "° ", ifelse(x > 0, "N", "S"))

# Converts a numeric array to an array of longitude labels
longitude <- function(x) 
    paste0(format(x, digits = 3), "° ", ifelse(x > 0, "E", "W"))


suicidal_map <- ggplot(new_data, 
                       aes(x = long,
                           y = lat,
                           group = group,
                           fill = Rate)) +
  geom_polygon(aes(x = long + 0.005, y = lat - 0.002),
               color = "grey50", size = 0.2, fill = "grey50") +
  geom_polygon(color = "gray10", size = 0.2) +
  coord_equal() +
  labs(title = "Choropleth Map: Suicidal Rate Among countries",
       fill = "Suicidal Rate") +
  theme_void() +
  theme(panel.background = element_rect(fill = NA, colour = "#cccccc"),
        text = element_text(family = "Arial Narrow", size = 8),
        plot.title = element_text(size = 12, face = "bold"),
        plot.margin = unit(c(0, 0.25, 0.0, 0.25), "in"),
        panel.border = element_rect(fill = NA, colour = "#cccccc"),
        legend.text = element_text(size = 8))

suicidal_map + 
  scale_y_continuous(labels = latitude) +
  scale_x_continuous(labels = longitude) +
  theme(axis.text = element_text(size = 8, colour = "#333333")) +
  ggsn::north(new_data, location = "bottomright", symbol = 10)
```


